### ISSUE TITLE
USB WiFi dongle

### ISSUE THREAD

**Issue by ghost** [longsleep/linux-pine64#15]
I am trying to plug a usb wifi dongle but without success. Actually I tried several of them and none works. When I try to compile the modules it fails. 

Is there a plan to make usb wifi dongle work?

**Comment by longsleep** [comment]
Feel free to create a tested pull request which add whatever wifi module. Please mention if non-free firmware is required in the PR.

**Comment by flakeman2** [comment]
I was able to get my usb wifi working by using a debian repo:

https://wiki.debian.org/rt2800usb

**Comment by tgrzybow** [comment]
I was not able to get my RA usb device working under debian, though I tried the instructions suggested I follow under https://wiki.debian.org/rt2800usb.

When I  issue the command "lsusb", this is what I see:
`Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 002: ID 148f:5372 Ralink Technology, Corp. RT5372 Wireless Adapter
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub`

But, when I "ip a", wlan0 does not show
and when I "ip link set wlan0 up" I get:
Cannot find device "wlan0"

Can't configure the device because I can't see it!

**Comment by tgrzybow** [comment]
Of course I did `apt-get install firmware-ralink` first, and rebooted the system.

**Comment by longsleep** [comment]
Please post the result for dmesg -w after you have plugged the device. The driver should be there.

**Comment by tgrzybow** [comment]
Here is the relevant section (I think):
`16.284480] [VFE]probe_work_handle start!
[   16.294724] [VFE]vfe_runtime_resume
[   16.315274] [VFE]..........................vfe clk open!.......................
[   16.328131] [VFE_WARN]vfe dphy clock is null
[   16.337672] [VFE]v4l2 subdev register input_num = 0
[   16.348018] [VFE]vfe sensor detect start! input_num = 0
[   16.359338] [VFE_WARN]NOT found this item:  hm5065, you can add this sensor in the sensor_list_t!
[   16.373975] [VFE]Sub device register "hm5065" i2c_addr = 0x3e start!
[   16.385863] [VFE_ERR]Error registering v4l2 subdevice No such device!
[   16.398184] [VFE_ERR]vfe sensor register check error at input_num = 0
[   16.410279] [VFE]v4l2 subdev register input_num = 1
[   16.416742] systemd-journald[1429]: Received request to flush runtime journal from PID 1
[   16.434520] axp81x_aldo1: Failed to create debugfs directory
[   16.445742] axp81x_dldo3: Failed to create debugfs directory
[   16.458570] axp81x_eldo3: Failed to create debugfs directory
[   16.469671] axp81x_aldo1: Failed to create debugfs directory
[   16.480708] [VFE]vfe sensor detect start! input_num = 1
[   16.491353] [VFE_WARN]NOT found this item:  gc2145, you can add this sensor in the sensor_list_t!
[   16.506437] [VFE]Sub device register "gc2145" i2c_addr = 0x78 start!
[   16.518451] [VFE_ERR]Error registering v4l2 subdevice No such device!
[   16.530550] [VFE_ERR]vfe sensor register check error at input_num = 1
[   16.542741] [VFE]V4L2 device registered as (null)
[   16.553087] [VFE]vfe_runtime_suspend
[   16.562093] [VFE]..........................vfe clk close!.......................
[   16.582469] [VFE]probe_work_handle end!
[   17.095049] libphy: 1c30000.eth: probed
[   17.104396] sunxi-gmac 1c30000.eth eth0: eth0: PHY ID 001cc915 at 0 IRQ poll (1c30000.eth-0:00)
[   23.001997] libphy: 1c30000.eth-0:00 - Link is Up - 1000/Full
[   30.730199] Bluetooth: Core ver 2.16
[   30.742174] NET: Registered protocol family 31
[   30.752526] Bluetooth: HCI device and connection manager initialized
[   30.765962] Bluetooth: HCI socket layer initialized
[   30.777338] Bluetooth: L2CAP socket layer initialized
[   30.788604] Bluetooth: SCO socket layer initialized
[   31.262610] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   31.275753] Bluetooth: BNEP filters: protocol multicast
[   31.288936] Bluetooth: BNEP socket layer initialized
[   31.474557] libphy: 1c30000.eth: probed
[   31.489250] sunxi-gmac 1c30000.eth eth0: eth0: PHY ID 001cc915 at 0 IRQ poll (1c30000.eth-0:00)
[   31.554409] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   37.388186] libphy: 1c30000.eth-0:00 - Link is Up - 1000/Full
[   37.394561] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready'

There seems to be no evidence of the RA driver!

Tom

**Comment by tgrzybow** [comment]
OK, this is interesting:

dmesg -w | grep wlan
[    7.750110] sunxi-wlan wlan.26: wlan_busnum (1)
[    7.755160] sunxi-wlan wlan.26: Missing wlan_power.
[    7.760606] sunxi-wlan wlan.26: wlan_power_name ((null))
[    7.766527] sunxi-wlan wlan.26: io_regulator_name (vcc-wifi-io)
[    7.773156] sunxi-wlan wlan.26: wlan_regon gpio=354  mul-sel=1  pull=-1  drv_level=-1  data=0
[    7.782688] sunxi-wlan wlan.26: wlan_hostwake gpio=355  mul-sel=6  pull=-1  drv_level=-1  data=0
[    7.792506] sunxi-wlan wlan.26: clk not config
[   13.433957] sunxi-wlan wlan.26: bus_index: 1
[   13.444373] sunxi-wlan wlan.26: check wlan io_regulator voltage: 1800000

**Comment by tgrzybow** [comment]
lsmod shows `cfg80211              356431  1 8723bs`  which is expected.

Could this be a hardware issue?  I'm trying to use a Panda Wireless PAU06 (which proves to work well on my Raspberry PI 2/3).  Flakeman2, what usb wifi hardware are you using?

**Comment by flakeman2** [comment]
I think that's the same one I'm using.  I bought this one on amazon:

https://www.amazon.com/gp/product/B00JDVRCI0/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1

I used longsleep's basic ubuntu xerial kernel/image:  

https://www.stdin.xyz/downloads/people/longsleep/pine64-images/ubuntu/

After booting up I added the debian repo and installed the firmware-ralink package.

**Comment by tgrzybow** [comment]
Yup, same one!  The one difference is that I am using longsleep's Debian kernel/image.  I think I'll try the Ubuntu image together with the Debian repos, since getting usb wifi working is very important to me.  Thanks Flakeman2 for your feedback!

**Comment by tgrzybow** [comment]
Same result with Ubuntu as with Debian.  It looks to be a hardware/powersupply issue, since this is what we see from ubuntu@localhost:~$ dmesg -w | grep wlan
`
[    8.268588] sunxi-wlan wlan.26: wlan_busnum (1)
[    8.273637] sunxi-wlan wlan.26: Missing wlan_power.
[    8.279081] sunxi-wlan wlan.26: wlan_power_name ((null))
[    8.285000] sunxi-wlan wlan.26: io_regulator_name (vcc-wifi-io)
[    8.291626] sunxi-wlan wlan.26: wlan_regon gpio=354  mul-sel=1  pull=-1  drv_level=-1  data=0
[    8.301153] sunxi-wlan wlan.26: wlan_hostwake gpio=355  mul-sel=6  pull=-1  drv_level=-1  data=0
[    8.310968] sunxi-wlan wlan.26: clk not config
[   17.974194] sunxi-wlan wlan.26: bus_index: 1
[   17.984910] sunxi-wlan wlan.26: check wlan io_regulator voltage: 1800000

`
The power-supply adapter is a Kootek 5V: 2500mA unit I use with my Pi 3.  Any comments?

**Comment by tgrzybow** [comment]
Yeah, I'm pretty sure it is some sort of hardware issue - but the power supply seems to be OK.  Now I'm thinking that my Pine64 USB ports are not delivering enough power to the dongle.  Strange the beast shows up when I issue "lsusb".  Now 'bout ready to give up.

**Comment by stephanemouton** [comment]
I've got the same problem (no wifi, same messages in dmesg than tgrzybow) but this time with the "official" pine wifi adaptor

**Comment by stephanemouton** [comment]
I've got the same problem (no wifi, same messages in dmesg than tgrzybow) but this time with the "official" pine wifi adaptor

**Comment by stephanemouton** [comment]
Correction: it was due to some configuration (using iwconfig) missing

**Comment by nsisodiya** [comment]
What is the solution ?? I am facing same problem !!

**Comment by stephanemouton** [comment]
I had to reapply the whole iwconfig setup from scratch because some initial steps were not performed
See http://askubuntu.com/questions/138472/how-do-i-connect-to-a-wpa-wifi-network-using-the-command-line for example
