### ISSUE TITLE
Error compiling sun4i-emac.o: implicit declaration of function ‘writesl’

### ISSUE THREAD

**Issue by baryluk** [longsleep/linux-pine64#16]
Hi Simon.

I was trying to build this kernel with some more stuff built as modules, and got this:

  CC [M]  drivers/net/ethernet/allwinner/sun4i-emac.o
drivers/net/ethernet/allwinner/sun4i-emac.c: In function ‘emac_outblk_32bit’:
drivers/net/ethernet/allwinner/sun4i-emac.c:200:2: error: implicit declaration of function ‘writesl’ [-Werror=implicit-function-declaration]
  writesl(reg, data, round_up(count, 4) / 4);
  ^
drivers/net/ethernet/allwinner/sun4i-emac.c: In function ‘emac_inblk_32bit’:
drivers/net/ethernet/allwinner/sun4i-emac.c:205:2: error: implicit declaration of function ‘readsl’ [-Werror=implicit-function-declaration]
  readsl(reg, data, round_up(count, 4) / 4);
  ^
drivers/net/ethernet/allwinner/sun4i-emac.c: In function ‘emac_start_xmit’:
drivers/net/ethernet/allwinner/sun4i-emac.c:490:2: error: implicit declaration of function ‘dev_consume_skb_any’ [-Werror=implicit-function-declaration]
  dev_consume_skb_any(skb);
  ^
cc1: some warnings being treated as errors

tree after:

commit 2d4c3da2c6adf3b0de46aba25c7cc6a5c90a3bb9
Author: Simon Eisenmann simon@longsleep.org
Date:   Mon Feb 22 23:23:57 2016 +0100

```
Hacked KVM so it actually works. Thanks to @apritzel for remembering the bug and what to fix.
```

custom .config file (started with sun50iw1p1smp_linux_defconfig ), but with existing stuff not touched.

Any ideas? Some missing header includes?

I am using gcc 5.3.1-16, and doing native compilation.

**Comment by longsleep** [comment]
Why do you need sun4i-emac? Makes no sense if you ask me and does not seem to support 64bit.
