### ISSUE TITLE
backport bsp2.0: drivers/net/wireless/rtl8723bs/include/ieee80211.h

### ISSUE THREAD

**Issue by rhkean** [longsleep/linux-pine64#19]
using:  gcc (Debian/Linaro 4.9.2-10) 4.9.2
make modules 
yields 19 screens of:

```
drivers/net/wireless/rtl8723bs/hal/OUTSRC/rtl8723b/<file_xyz>.o: In function `is_zero_mac_addr':
/root/linux-pine64/drivers/net/wireless/rtl8723bs/include/ieee80211.h:1333: multiple definition of `is_zero_mac_addr'
drivers/net/wireless/rtl8723bs/core/rtw_cmd.o:/root/linux-pine64/drivers/net/wireless/rtl8723bs/include/ieee80211.h:1333: first defined here
```

and exits with a 2
and prevents the rest of the modules from compiling

when I copied that file out of the bsp2.0 tree, the driver compiled and the rest of the driver tree compiled.

**Comment by rhkean** [comment]
@longsleep 
this is probably invalid.  My kernel panic'd almost immediately, as an FYI.... here you go.  😄

**Comment by longsleep** [comment]
This driver is beyond repair. Do not compile it. Also i chose to ignore BSP 2.0 tree - do not use it.

**Comment by rhkean** [comment]
That's what I figured you would say.  :smile: 

but, I figured that it was better to bring it to your attention in case you knew something that I didn't.

I would recommend/request that you change the default config to mark it as Not Set instead of Module.
