### ISSUE TITLE
Apt package for linux-image-extra-3.10.101-4-pine64-longsleep missing?

### ISSUE THREAD

**Issue by faun** [longsleep/linux-pine64#23]
Hi there,

I'm attempting to install Docker on your Ubuntu Xenial builds for Pine64, and I'm attempting to install aufs support, and in doing so, I'm running `sudo apt-get install linux-image-extra-3.10.101-4-pine64-longsleep` and coming up empty:

```
No package matching 'linux-image-extra-3.10.101-4-pine64-longsleep' is available
```

Do you have any suggestions? I looked at https://launchpad.net/~longsleep and saw no packages listed there. Is there a PPA that I need to add? Does that package not exist?

I apologize if I've posted this issue in the wrong place.

Thanks,
Faun

**Comment by longsleep** [comment]
Thete are no packages - also Docker works out of the box including aufs support.
