### ISSUE TITLE
Using this kernel source for Android?

### ISSUE THREAD

**Issue by NHellFire** [longsleep/linux-pine64#25]
Does anyone know how I can use this source to build an Android kernel?
Kernel builds and boots fine, but only one USB ports is functional. I'm guessing that's caused by missing DTBs, but I can't figure out how to build the dt.img and the original Android kernel doesn't have one.

**Comment by longsleep** [comment]
I saw someone doing it - so i guess it works. Check the Pine64 forum for details.

**Comment by Phoenix09** [comment]
Could you be more specific?
All I can find is [this](http://forum.pine64.org/showthread.php?tid=1714)
