### ISSUE TITLE
Update to 3.10.104

### ISSUE THREAD

**Issue by NeQuissimus** [longsleep/linux-pine64#37]
Would you be able to update the kernel to 3.10.104 (see https://cdn.kernel.org/pub/linux/kernel/v3.x/ChangeLog-3.10.104) to patch DirtyCOW (https://dirtycow.ninja/)?

**Comment by longsleep** [comment]
Yes i will patch up to latest soon.

**Comment by longsleep** [comment]
Done, 7b00e2938e671b172f56328363b2940927dab707

**Comment by ra100** [comment]
Will you create build/release so someone (like me) without experience of kernel building can use this fix?

**Comment by longsleep** [comment]
Relase is done and available through the usual update script.

**Comment by longsleep** [comment]
Sure - i expect it for today if testing goes well
