### ISSUE TITLE
Merge 'pine64-hacks-1.2' to 'pine64-hacks-1.2-drm'

### ISSUE THREAD

**Issue by ghost** [longsleep/linux-pine64#40]
Please merge branch 'pine64-hacks-1.2' into branch 'pine64-hacks-1.2-drm'.
I've tested this scenario with commit tag '3.10.104-1-pine64' and did not see any issues.

**Comment by longsleep** [comment]
Done in 2fd24ecb83a492f1d6b0ef422a61fe38c92c78e8
