### ISSUE TITLE
REQUEST: CONFIG_VXLAN for Docker Network support

### ISSUE THREAD

**Issue by utdrmac** [longsleep/linux-pine64#51]
Per this comment/conversation: https://github.com/docker/machine/issues/2753#issuecomment-232174912

I'm attempting to use my 4 Pines as a Docker swarm. I've upgraded/compiled the latest version of Docker (17.04) and still cannot use overlay networks due to kernel feature missing.

```
"Error": "subnet sandbox join failed for \"10.0.0.0/24\": error creating vxlan interface: operation not supported",
```

For the next kernel release, please enable VXLAN, possibly as a module (to keep bloat down)

**Comment by atzoum** [comment]
vxlan has already been enabled, please refer to https://github.com/longsleep/linux-pine64/pull/50

**Comment by utdrmac** [comment]
@atzoum I did see #50 but it must not have been released yet because I just attempted to modprobe and it isn't there.

```
root@pine51:~# pine64_update_kernel.sh
Checking for update ...
You are already on latest version - abort.
root@pine51:~# modprobe vxlan
modprobe: FATAL: Module vxlan not found in directory /lib/modules/3.10.104-2-pine64-longsleep
root@pine51:~# uname -a
Linux pine51 3.10.104-2-pine64-longsleep #113 SMP PREEMPT Thu Dec 15 21:46:07 CET 2016 aarch64 aarch64 aarch64 GNU/Linux
root@pine51:~#
root@pine51:~# find /lib/ -name "*vx*"
root@pine51:~#
```

**Comment by umiddelb** [comment]
Hi @utdrmac ,

you might want to try a mainline kernel on the Pine64 with better Docker support. The Armbian people provide [nightly build images](https://www.armbian.com/donate/?f=https://dl.armbian.com/pine64/Ubuntu_xenial_dev_nightly.7z) containing a mainline kernel. At this time, I'm quite happy running a 4.9.13 kernel on the Pine64. 

Cheers
Uli

**Comment by longsleep** [comment]
I supposed this is resolved. Please reopen when still an issue.

**Comment by utdrmac** [comment]
It was only resolved by switching to another distro. :-(
