### ISSUE TITLE
is there any plan to upgrade the linux kernel to 4.x?

### ISSUE THREAD

**Issue by ochinchina** [longsleep/linux-pine64#53]
some new functions depends on the Linux kernel 4.x and they can't work on linux kernel 3.10.

Is there any plan to upgrade the Linux kernel to 4.x? if the kernel can be upgrade to latest it is better.

**Comment by longsleep** [comment]
This Kernel tree is based on whatever is provided in the BSP by the SoC vendor (in this case Allwinner). Whenever there is an upgrade i might consider to pull in changes. 

If you are interested in running a mainline(ish) Kernel, check out http://linux-sunxi.org/Linux_mainlining_effort for the community progress on that.
