### ISSUE TITLE
Badsig

### ISSUE THREAD

**Issue by phr34k0** [longsleep/linux-pine64#58]
![image](https://user-images.githubusercontent.com/13272249/28688994-8a0d602e-7346-11e7-837d-77e7b108c978.png)

Running Debian Mate (3.10.102 BSP 2) from https://www.pine64.pro/downloads/linux-images/

**Comment by longsleep** [comment]
The signature is not invalid. Most likely your Pine64 has an issue with the power supply and failed to correctly download/verify - even more likely as in your screenshot also curl failed in free().

**Comment by phr34k0** [comment]
@longsleep That appears on random. Curl works upon retrying. My Pine came with power supply from kickstater Pine64+ as a package. Everything works except your kernel

**Comment by longsleep** [comment]
Well - it probably runs a variant of my Kernel with the image you flashed. Try replacing the PSU - there are multiple threads in the Pine64 forum about power supply issues - nothing i can do.
