### ISSUE TITLE
Pine does not boot (randomly)

### ISSUE THREAD

**Issue by lampi87** [longsleep/linux-pine64#62]
Hello,

Unfortunately my boot randomly does not boot on restart.
Ethernet LED stay dark.
After several retries it boots.

U-boot and Kernel is up-to-date, based on update scripts

I already tried decreasing eth speed with `sudo ethtool -s eth0 speed 100 duplex full`
But it did not solve the problem.

Any ideas?

Best regards,
Alexander

**Comment by longsleep** [comment]
This is a bug tracker and not a support forum. There can be many reasons why your device does not boot - please try the pine64 forum.
