### ISSUE TITLE
Switch to 4.10 kernel

### ISSUE THREAD

**Issue by mstfacmly** [longsleep/linux-pine64#66]
Considering the 4.10 kernel [supports PINE64 by default](https://www.linux.com/news/2017/2/linux-kernel-410-released-happy-anniversary), why is the 3.10 one still being used?

Wouldn't it make more sense to use a more up-to-date kernel as basis, with minimum hacking?

**Comment by longsleep** [comment]
Well this a Kernel 3.10 kernel based on the BSP as provided by the SoC vendor. At this time there is no other (newer) Kernel which supports all the features from this Kernel tree. See https://linux-sunxi.org/Mainlining_Effort (A64 column for details and progress).
