### ISSUE TITLE
Why is dsi_div value computed as bpp / lanes?

### ISSUE THREAD

**Issue by openedev** [longsleep/linux-pine64#68]
Any idea why is dsi_div value is depends on bpp and lanes. since dsi_div indeed compute the pll_rate making default to 4 can't work in all the LCD panels with different lane size?

https://github.com/longsleep/linux-pine64/blob/pine64-hacks-1.2/drivers/video/sunxi/disp2/disp/de/lowlevel_sun50iw1/disp_al.c#L213

**Comment by longsleep** [comment]
No clue, this whole video driver is a mess made by the hardware vendor. Best do not look at it unless you have to. This is just an import of the BSP as provided - if you need specific advice either get in contact with the author of that particular driver or get involved with the https://linux-sunxi.org/ community.

**Comment by openedev** [comment]
Thanks, any mode of communication to Allwinner?
